//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace American_Football_Scoreboard.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.2.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15:00")]
        public string DefaultPeriod {
            get {
                return ((string)(this["DefaultPeriod"]));
            }
            set {
                this["DefaultPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public string DefaultPlay {
            get {
                return ((string)(this["DefaultPlay"]));
            }
            set {
                this["DefaultPlay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputPath {
            get {
                return ((string)(this["OutputPath"]));
            }
            set {
                this["OutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Goal")]
        public string GoalText {
            get {
                return ((string)(this["GoalText"]));
            }
            set {
                this["GoalText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string TimeoutsPerHalf {
            get {
                return ((string)(this["TimeoutsPerHalf"]));
            }
            set {
                this["TimeoutsPerHalf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + G")]
        public string HotKeyStartStopGameClock {
            get {
                return ((string)(this["HotKeyStartStopGameClock"]));
            }
            set {
                this["HotKeyStartStopGameClock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + P")]
        public string HotKeyStartStopPlayClock {
            get {
                return ((string)(this["HotKeyStartStopPlayClock"]));
            }
            set {
                this["HotKeyStartStopPlayClock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + N")]
        public string HotKeyNewPlayClock {
            get {
                return ((string)(this["HotKeyNewPlayClock"]));
            }
            set {
                this["HotKeyNewPlayClock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + C")]
        public string HotKeyClearClocks {
            get {
                return ((string)(this["HotKeyClearClocks"]));
            }
            set {
                this["HotKeyClearClocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + D")]
        public string HotKeyNextDown {
            get {
                return ((string)(this["HotKeyNextDown"]));
            }
            set {
                this["HotKeyNextDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + Q")]
        public string HotKeyNextPeriod {
            get {
                return ((string)(this["HotKeyNextPeriod"]));
            }
            set {
                this["HotKeyNextPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + 1")]
        public string HotKeyAway1 {
            get {
                return ((string)(this["HotKeyAway1"]));
            }
            set {
                this["HotKeyAway1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + 2")]
        public string HotKeyAway2 {
            get {
                return ((string)(this["HotKeyAway2"]));
            }
            set {
                this["HotKeyAway2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + 3")]
        public string HotKeyAway3 {
            get {
                return ((string)(this["HotKeyAway3"]));
            }
            set {
                this["HotKeyAway3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + 4")]
        public string HotKeyAway6 {
            get {
                return ((string)(this["HotKeyAway6"]));
            }
            set {
                this["HotKeyAway6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + 5")]
        public string HotKeyHome1 {
            get {
                return ((string)(this["HotKeyHome1"]));
            }
            set {
                this["HotKeyHome1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + 6")]
        public string HotKeyHome2 {
            get {
                return ((string)(this["HotKeyHome2"]));
            }
            set {
                this["HotKeyHome2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + 7")]
        public string HotKeyHome3 {
            get {
                return ((string)(this["HotKeyHome3"]));
            }
            set {
                this["HotKeyHome3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + 8")]
        public string HotKeyHome6 {
            get {
                return ((string)(this["HotKeyHome6"]));
            }
            set {
                this["HotKeyHome6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int RefreshInterval {
            get {
                return ((int)(this["RefreshInterval"]));
            }
            set {
                this["RefreshInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt + Shift + 9")]
        public string HotKeyPossession {
            get {
                return ((string)(this["HotKeyPossession"]));
            }
            set {
                this["HotKeyPossession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdvanceQuarter {
            get {
                return ((bool)(this["AdvanceQuarter"]));
            }
            set {
                this["AdvanceQuarter"] = value;
            }
        }
    }
}
